# 12-174 Adding configuration files
# this is the file to do the network setup (step 3 of 3) - see client-pod for container config
apiVersion: v1
kind: Service
metadata:
  name: client-node-port
spec:
  type: NodePort
  ports:
  - port: 3050    # don't know why '-' indenting has to be thus, else error - check this
    targetPort: 3000
    nodePort: 31515
  selector:
    component: web
