# 12-174 Adding configuration files
# this is the file to do the config (step 2 of 3) - see client-node-port for networking setup
apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:   # 1 container in this pod (discussed 12-176)
    - name: client
      image: peternjenkin/multi-client
      ports:
      - containerPort: 3000   # nginx is still listening on port 3000 (more setup required)